version: '3'
services:
  react-client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /home/cryptodash/node_modules
      - .:/home/cryptodash
